### ISSUE TITLE
1002

### ISSUE THREAD

**Issue by thin-lizard** [WeberLab-UW/LS-phd#1]
- fg transcripts to dataverse
- 504 dataset - choose topic + set up mtg w KC - 10/11
- RSR - hypotheses 
- ....

```[tasklist]
### Tasks
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/17
- [ ] https://github.com/PugetSoundClinic-PIT/eager-survey/issues/5
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/19
- [ ] 570 reading - baronov
- [ ] nosegrind // keys
- [ ] 508 hw
- [ ] 500: skim + search
- [x] calendar // deadlines
- [x] 570 - set mtg
- [x] gp5 data collection - y1 // and paper queue
- [x] 504 reading
- [x] overleaf - sections
- [x] 500 survey + signup
- [x] fare fair next steps
- [ ] sync ob vault
- [ ] Net bargaining schedule // PRT schedule
- [ ] feedly
- [ ] email DU
- [ ] reading list for phd wiki
- [ ] https://github.com/BITS-Research/DRC/issues/31
- [ ] agenda https://github.com/PugetSoundClinic-PIT/LS-phd/issues/4
- [x] 500 reading
```
