### ISSUE TITLE
0122

### ISSUE THREAD

**Issue by thin-lizard** [WeberLab-UW/LS-phd#103]
- [ ] [DRC new outline | LS-phd#19](https://github.com/PugetSoundClinic-PIT/LS-phd/issues/19)
    - [ ] abstract
    - [ ] 2x contributions - 
    - [ ] consistent terminology
    - [ ] focus group excerpts
    - [ ] discussion pgh
    - [ ] citations

- #101 

```[tasklist]
### Tasks
- [ ] BOOK REVIEW
- [x] CORNELL PREP
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/105
- [x] undergrad ra?
- [ ] 531 writing clinic
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/94
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/92
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/104
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/102
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/65
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/101
- [ ] https://github.com/BITS-Research/DRC/issues/35
- [ ] 531 policy brief ex
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/75
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/43
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/55
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/54
- [ ] email meg young
- [ ] project imeline - workign w ols, farefair, ...
- [ ] 571 assgt
- [ ] 501 assgt - read abbott
- [x] 501
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/5
- [ ] spring courses
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/77
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/78
```
