### ISSUE TITLE
0129

### ISSUE THREAD

**Issue by thin-lizard** [WeberLab-UW/LS-phd#110]
- [ ] [DRC new outline | LS-phd#19](https://github.com/PugetSoundClinic-PIT/LS-phd/issues/19)
    - [ ] abstract
    - [ ] 2x contributions - 
    - [ ] consistent terminology
    - [ ] focus group excerpts
    - [ ] discussion pgh
    - [ ] citations

- https://github.com/PugetSoundClinic-PIT/LS-phd/issues/102
- #62 
- #65 

```[tasklist]
### Tasks
- [ ] BOOK REVIEW
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/108
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/65
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/107
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/106
- [ ] https://github.com/BITS-Research/DRC/issues/35
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/43
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/55
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/54
- [ ] email meg young
- [ ] project imeline - workign w ols, farefair, ...
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/77
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/78
- [x] 501 hw
- [ ] 501 assgt
- [x] 531 grading
- [x] 531 policy brief ex
- [x] 531 writing clinic
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/5
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/104
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/111
- [x] email tanu
```
