### ISSUE TITLE
0205

### ISSUE THREAD

**Issue by thin-lizard** [WeberLab-UW/LS-phd#113]
- [ ] [DRC new outline | LS-phd#19](https://github.com/PugetSoundClinic-PIT/LS-phd/issues/19)
    - [x] abstract
    - [x] 2x contributions - 
    - [ ] consistent terminology
    - [x] focus group excerpts
    - [x] discussion pgh
    - [ ] citations
    - [ ] we know we're reporting on a small n -- but we still feel it's important

- https://github.com/PugetSoundClinic-PIT/LS-phd/issues/102

```[tasklist]
### Tasks
- [x] 351 slides
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/102
- [ ] BOOK REVIEW
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/65
- [ ] HSSDI https://docs.google.com/forms/d/e/1FAIpQLSdcnhqZSUEJQp-RT1T30RLV_pYfme46trbypwZbs9_VU23ChQ/viewform -- DUE 23rd
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/119
- [ ] 501 assgt
- [ ] revisit inversi for gp
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/112
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/79
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/80
- [x] resp to katie davis
- [x] abd revisions
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/114
- [x] drc paper - disc. paragraph
- [ ] INDEPENDENT STUDY!?
- [x] soft search journal & protocol
- [ ] fare fair norm
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/120
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/104
- [ ] https://github.com/BITS-Research/DRC/issues/35
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/43
- [x] 501 hw
- [x] 531 grading
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/83
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/55
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/54
- [ ] email meg young
- [ ] project imeline - workign w ols, farefair, ...
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/5
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/116
- [x] ch 1 hacker hoaxer for tues
- [x] 531 clinic
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/115
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/117
- [x] ABD paper --> for tues - pass thru findings & disc.; stick to storyline
```
