### ISSUE TITLE
0226

### ISSUE THREAD

**Issue by thin-lizard** [WeberLab-UW/LS-phd#122]
- [ ] [DRC new outline | LS-phd#19](https://github.com/PugetSoundClinic-PIT/LS-phd/issues/19)
    - [ ] 2x contributions - 
    - [ ] consistent terminology
    - [ ] citations
    - [ ] we know we're reporting on a small n -- but we still feel it's important

- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/102
    - [x] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/119
    - [x] resp to shuxuan
    - [ ] clean notes from ols mtg
    - [ ] 2x check NYC ordinance re: language & risks of piecing together pricing algs

```[tasklist]
### Tasks
- [x] interview prep
- [x] email melanie
- [x] danielle mtg prep
- [x] 351 grading
- [ ] BOOK REVIEW
- [x] emma agenda
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/65
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/68
- [x] 501 paper
- [x] 501 hw
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/121
- [ ] revisit inversi for gp
- [ ] fare fair norm
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/104
- [ ] https://github.com/BITS-Research/DRC/issues/35
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/43
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/55
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/54
- [ ] email meg young
- [ ] project imeline - workign w ols, farefair, ...
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/5
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/116
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/117
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/85
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/86
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/124
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/126
```
