### ISSUE TITLE
0325

### ISSUE THREAD

**Issue by thin-lizard** [WeberLab-UW/LS-phd#130]
```[tasklist]
### Tasks
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/121
- [x] DRC - edits w eva -> methods; ->
- [x] adv form
- [ ] https://labor.washington.edu/washington-state-labor-research-grant
- [x] ABWMP survey
- [ ] resp to shuxuan
- [ ] venues for op ed
- [x] 570 - 2
- [ ] ff norm ->
- [x] city council mtg thurs
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/65
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/128
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/125
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/43
- [x] lib book
- [x] tnc prescreened datasets
- [x] drop sts class; email nassim
- [x] tuition
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/132
- [x] unique IDs for surveys in qualtrics
- [x] 573 reading // disc
- [ ] directory Q
- [x] set deadlines // finish q goals
- [x] issues re: class assigments, annual review / committee
- [ ] teaching practica - follow up w tanu & melanie
- [x] 573 ...
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/135
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/137
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/138
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/139
- [ ] https://onlinelibrary.wiley.com/pb-assets/assets/14678543/cfp/BJIR-CFP-Technological-Change-Power-and-Work-1710467358137.pdf
- [x] 525 wk 2
- [x] 525 wk 3
- [ ] 2nd phase of policy reaearch plan - post desc., where to investigate & how
- [ ] sarah project
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/140
- [ ] follow up w charlotte
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/143
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/141
- [ ] https://docs.google.com/document/d/1RsZmmJ9oOCj0qomyHghdPYOlKfcmiSsmni1h4zm5wCw/edit
- [ ] RSR....
- [ ] draft tanu presentation
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/142
- [ ] https://waim.network/
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/144
- [ ] council mtgs: tues & thurs
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/147
- [ ] https://github.com/PugetSoundClinic-PIT/gig-policies/issues/11
```
