### ISSUE TITLE
0413

### ISSUE THREAD

**Issue by thin-lizard** [WeberLab-UW/LS-phd#148]
```[tasklist]
### Tasks
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/121
- [ ] resp to shuxuan
- [ ] ff norm ->
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/65
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/125
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/43
- [ ] directory Q
- [ ] teaching practica - follow up w tanu & melanie
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/140
- [ ] follow up w charlotte
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/143
- [ ] https://docs.google.com/document/d/1RsZmmJ9oOCj0qomyHghdPYOlKfcmiSsmni1h4zm5wCw/edit
- [ ] https://waim.network/
- [x] council mtgs: tues & thurs
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/147
- [x] sarah project
- [ ] https://github.com/PugetSoundClinic-PIT/gig-policies/issues/11
- [x] 525 week 4
- [x] 573 - schedule meeting w jaime
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/144
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/154
- [ ] draft tanu presentation
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/141
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/149
- [x] sarah repo // index doc
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/151
- [x] email MB
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/152
- [x] bump email to andrea
- [x] 525 week 5
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/156
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/157
```
