### ISSUE TITLE
0429

### ISSUE THREAD

**Issue by thin-lizard** [WeberLab-UW/LS-phd#158]
- [ ] [Asymm by Design revisions - Findings & Disc. sections | LS-phd#121](https://github.com/PugetSoundClinic-PIT/LS-phd/issues/121)
- [ ] resp to shuxuan
- [ ] ff norm ->
- [x] [HB Scholarship - May 6 | LS-phd#125](https://github.com/PugetSoundClinic-PIT/LS-phd/issues/125)
- [ ] [CSCW blog post | LS-phd#43](https://github.com/PugetSoundClinic-PIT/LS-phd/issues/43)
- [ ] directory Q
- [x] teaching practica - follow up w tanu & melanie
- [ ] follow up w charlotte
- [x] [agenda 0418 | LS-phd#143](https://github.com/PugetSoundClinic-PIT/LS-phd/issues/143)
- [ ] https://docs.google.com/document/d/1RsZmmJ9oOCj0qomyHghdPYOlKfcmiSsmni1h4zm5wCw/edit
- [ ] https://waim.network/
- [ ] [ABWMP study - OSF PREREG | gig-policies#11](https://github.com/PugetSoundClinic-PIT/gig-policies/issues/11)
- [ ] [DISP ARB paper - steps to submission | LS-phd#141](https://github.com/PugetSoundClinic-PIT/LS-phd/issues/141)
- [ ] [POLICY WORK | LS-phd#149](https://github.com/PugetSoundClinic-PIT/LS-phd/issues/149)
- [x] [agenda 04.22 | LS-phd#151](https://github.com/PugetSoundClinic-PIT/LS-phd/issues/151)
- [ ] email MB
- [x] [to discuss w NW - | LS-phd#152](https://github.com/PugetSoundClinic-PIT/LS-phd/issues/152)
- [x] [agenda 04.29 | LS-phd#157](https://github.com/PugetSoundClinic-PIT/LS-phd/issues/157)
```[tasklist]
### Tasks
- [x] 573 - set of research articles
- [x] 573 PROTOTYPE
- [ ] GEOG WK 6
- [ ] GEOG WK 7
- [x] GEOG WK 8
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/153
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/155
- [x] email kennedy
- [ ] email du
- [ ] email rdu
- [x] email JI
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/150
- [ ] GEOG WK 9
- [x] 573 - DRAFTING & pilot study?
- [ ] pidoux articlce
- [x] leased among us
```
