### ISSUE TITLE
10.09

### ISSUE THREAD

**Issue by thin-lizard** [WeberLab-UW/LS-phd#38]
- [x] [Week 1 next steps | eager-survey#5](https://github.com/PugetSoundClinic-PIT/eager-survey/issues/5)
- [ ] [DRC new outline | LS-phd#19](https://github.com/PugetSoundClinic-PIT/LS-phd/issues/19)
    - [x] M
    - [x] T
    - [ ] W
    - [ ] R
    - [ ] F 
- [x] 570 reading - baronov
- [x] nosegrind // keys
- [ ] extra qs for RSR survey
- [x] 508 hw - tues 4:30
- [x] 504 assgt - wed
- [x] agenda https://github.com/PugetSoundClinic-PIT/LS-phd/issues/20
- [ ] [networked bargaining paper - GP + focus groups | DRC#31](https://github.com/BITS-Research/DRC/issues/31)
- [ ] agenda https://github.com/PugetSoundClinic-PIT/LS-phd/issues/4
- [x] 500: skim + search - 
    - [ ] find LIS 505 notes
- [ ] sync ob vault
- [ ] Net bargaining schedule // PRT schedule
- [ ] feedly
- [ ] email DU
- [ ] reading list for phd wiki
- [ ] focus group transcripts to dataverse
- [x] #21 
- [x] #29 
- [ ] RSR draft survey jawn
- [ ] https://github.com/PugetSoundClinic-PIT/eager-survey/issues/9
