### ISSUE TITLE
10.16

### ISSUE THREAD

**Issue by thin-lizard** [WeberLab-UW/LS-phd#40]
- [ ] RSR draft survey jawn
- [x] https://github.com/PugetSoundClinic-PIT/eager-survey/issues/9
- [ ] [DRC new outline | LS-phd#19](https://github.com/PugetSoundClinic-PIT/LS-phd/issues/19)
    - [x] M
    - [ ] T
    - [ ] W
    - [ ] R
    - [x] F 
- [ ] extra qs for RSR survey
- [x] [networked bargaining paper - GP + focus groups | DRC#31](https://github.com/BITS-Research/DRC/issues/31)
- [ ] Net bargaining schedule // PRT schedule
- [ ] sync ob vault
- [ ] feedly
- [ ] email DU
- [ ] HCDE etc
- [ ] reading list for phd wiki
- [ ] focus group transcripts to dataverse

```[tasklist]
### Tasks
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/3
- [ ] https://github.com/PugetSoundClinic-PIT/Fare-Fair/issues/18
- [x] 500: find LIS 505 notes
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/21
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/4
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/8
- [x] 1018 agenda
- [x] cscw reimbursement
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/30
- [x] reading list -> google sheet ->
- [ ] questionnaire for interviews
```
