### ISSUE TITLE
10.23

### ISSUE THREAD

**Issue by thin-lizard** [WeberLab-UW/LS-phd#42]
- [ ] [DRC new outline | LS-phd#19](https://github.com/PugetSoundClinic-PIT/LS-phd/issues/19)
    - [ ] M
    - [ ] T
    - [ ] W
    - [ ] R
    - [ ] F 
- [ ] DRC net bargaining analysis 
- [ ] for the coalition/ gig worker center paper ? https://www.britsoc.co.uk/media/26353/wes_si_cfp_dl310124.pdf

```[tasklist]
### Tasks
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/9
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/3
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/22
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/31
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/2
- [ ] https://github.com/nniiicc/eager-survey/issues/9
- [ ] RSR - questionnarire for interviews
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/43
- [ ] HCDE etc
- [ ] S. Ghoshal
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/44
- [ ] https://github.com/nniiicc/eager-survey/issues/13
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/23
```
