### ISSUE TITLE
10.30

### ISSUE THREAD

**Issue by thin-lizard** [WeberLab-UW/LS-phd#47]
- [ ] [DRC new outline | LS-phd#19](https://github.com/PugetSoundClinic-PIT/LS-phd/issues/19)
    - [x] M
    - [ ] T
    - [x] W
    - [ ] R
    - [ ] F 
- [ ] DRC net bargaining analysis 
- [ ] for the coalition/ gig worker center paper ? https://www.britsoc.co.uk/media/26353/wes_si_cfp_dl310124.pdf

```[tasklist]
### Tasks
- [x] EMAIL KC
- [x] RSR - questionnarire for interviews
- [ ] HCDE etc
- [ ] S. Ghoshal
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/48
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/45
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/23
- [ ] https://github.com/nniiicc/eager-survey/issues/9
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/46
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/43
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/32
- [x] 508 lecture
- [x] 570 reading - disc + pres
- [x] email sophie
- [x] check interview scheduling optoins
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/10
- [ ] https://github.com/PugetSoundClinic-PIT/Fare-Fair/issues/18
- [ ] 504 assgt catchup --> [q feedback on previous pt 3s]
- [ ] travis
- [ ] choose 1 output for the quarter --> 'infrastructure' repo // trace ethnography - RSR
- [ ] demo survey instrument & take notes - RSR
- [x] 508 eval
- [ ] add disrupting dc review to project queue
- [ ] https://arxiv.org/pdf/2301.04991.pdf
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/50
- [ ] CSCW submission -> https://cscw.acm.org/2024/index.php/submit-papers/
- [x] 500 readings
- [ ] RSR - clean up landing page and confirmation emails
```
