### ISSUE TITLE
11.06

### ISSUE THREAD

**Issue by thin-lizard** [WeberLab-UW/LS-phd#51]
- [ ] [DRC new outline | LS-phd#19](https://github.com/PugetSoundClinic-PIT/LS-phd/issues/19)
    - [ ] M
    - [ ] T
    - [ ] W
    - [ ] R
    - [ ] F 
- [ ] RSR - 
    - [x] clean up landing page and confirmation emails
        - [x] int start next week
    - [x] https://arxiv.org/pdf/2301.04991.pdf
    - [x] consent form
    - [x] resend eva invite
    - [x] decoupling of research project & its software -> interview thread

```[tasklist]
### Tasks
- [ ] CSCW submission -> https://cscw.acm.org/2024/index.php/submit-papers/
- [ ] HCDE etc
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/55
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/24
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/45
- [ ] https://github.com/nniiicc/eager-survey/issues/9
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/43
- [x] 508 lecture
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/33
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/11
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/50
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/5
- [x] 570 reading
- [ ] https://github.com/PugetSoundClinic-PIT/Fare-Fair/issues/18
- [ ] 504 assgt catchup --> [q feedback on previous pt 3s]
- [ ] travis
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/52
- [ ] https://github.com/nniiicc/eager-survey/issues/18
- [x] 500 readings
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/54
- [x] email about book review
```
