### ISSUE TITLE
11.13

### ISSUE THREAD

**Issue by thin-lizard** [WeberLab-UW/LS-phd#57]
- [ ] [DRC new outline | LS-phd#19](https://github.com/PugetSoundClinic-PIT/LS-phd/issues/19)
    - [ ] M
    - [ ] T
    - [ ] W
    - [ ] R
    - [ ] F 

RSR - 
- [x] - case data paper for thurs
- [x] set interview reminders
- [x] protocol for friday meeting
- [x] interview prep
- [x] participant + gift card spreadsheets
- [ ] memo + revise questionnaire

```[tasklist]
### Tasks
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/39
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/50
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/45
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/11
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/43
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/5
- [x] CSCW submission -> https://cscw.acm.org/2024/index.php/submit-papers/
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/55
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/54
- [x] 508 lecture
- [ ] 504 assgt catchup --> [q feedback on previous pt 3s]
- [ ] 500 readings
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/12
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/34
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/26
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/35
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/13
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/59
```
