### ISSUE TITLE
11.27--12.04

### ISSUE THREAD

**Issue by thin-lizard** [WeberLab-UW/LS-phd#60]
- [ ] [DRC new outline | LS-phd#19](https://github.com/PugetSoundClinic-PIT/LS-phd/issues/19)
    - [ ] M
    - [x] T - background
    - [x] W - clean intro and background; and that pgh in discussion section
    - [x] R - abstract & edits to overleaf 
    - [ ] F 

RSR - 
- [x] memo + revise questionnaire - FOR TUES
- [x] interview prep
- [x] update spreadsheet and new interview reminders (if needed)

```[tasklist]
### Tasks
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/5
- [ ] https://github.com/nniiicc/eager-survey/issues/23
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/59
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/43
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/13
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/45
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/55
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/54
- [x] application review
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/36
- [x] 508 lecture
- [x] 504 assgt catchup --> [q feedback on previous pt 3s]
- [x] 500 readings
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/28
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/14
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/61
- [ ] drc op ed
- [ ] https://cdt.org/job/summer-2024-internships/
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/63
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/16
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/37
- [ ] BOOK REVIEW
```
