### ISSUE TITLE
12.11

### ISSUE THREAD

**Issue by thin-lizard** [WeberLab-UW/LS-phd#64]
- [ ] [DRC new outline | LS-phd#19](https://github.com/PugetSoundClinic-PIT/LS-phd/issues/19)
    - [ ] abstract
    - [ ] 2x contributions - 
    - [ ] consistent terminology
    - [ ] focus group excerpts
    - [ ] discussion pgh
    - [ ] citations

```[tasklist]
### Tasks
- [x] https://cdt.org/job/summer-2024-internships/
- [x] CV // website
- [x] reach out again to andrew
- [x] otter transcripts ->
- [ ] https://github.com/BITS-Research/DRC/issues/35
- [x] eva ml for pit feedback
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/5
- [ ] https://github.com/nniiicc/eager-survey/issues/23
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/43
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/55
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/54
- [ ] BOOK REVIEW
- [ ] winter q milestones
- [ ] email meg young
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/65
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/91
- [ ] documentation ex.s
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/71
- [ ] 531 lessons // activities
- [ ] 531 policy brief ex
```
