### ISSUE TITLE
summer 2k24

### ISSUE THREAD

**Issue by thin-lizard** [WeberLab-UW/LS-phd#65]
```[tasklist]
### Tasks
- [x] CDT
- [x] https://fpf.org/us-policy-internships/ - JAN 28
- [x] https://www.upturn.org/join/2024-summer-fellowship/ - FEB 4 -
- [x] https://laborcenter.berkeley.edu/labor-summer-internship/ - FEB 9
- [x] https://urban.wd1.myworkdayjobs.com/en-US/Urban-Careers/job/Research-Intern--Metropolitan-Housing-and-Communities-_R-801526 - ROLLING
- [x] https://intern.usajobs.gov/job/775700600 -- 2/22
- [x] https://intern.usajobs.gov/job/775701500 -- 2/22
- [x] https://laborcenter.ucsd.edu/labor-summer-2024/index.html - FEB 23
- [x] https://www.brookings.edu/careers/internships/ - FEB 25
- [x] https://law.ucdavis.edu/centers/uc-davis-labor-and-community-center/labor-summer/2024 - MAR 1
- [x] https://www.aclu.org/careers/internships/apply/?job=7229436002&type=internships - MAR 15
- [x] https://www.aclu.org/careers/internships/apply/?job=7229639002&type=internships - ^^ (past prioritiy)
- [x] https://www.citizen.org/internships/ - check back for addtl research internships. - MAR 25
- [x] OECD
- [x] GOOGLE Public Policy -https://www.google.com/policyfellowship/usa/hosts/ - ' APR 11
- [x] new america
- [x] king co
- [ ] https://www.bayareacouncil.org/internship-program/
- [ ] cloud kitchens
- [ ] https://lgr.ag.ny.gov/ords/f?p=136:10:::::P10_LGR_JOB_ID,P10_POSITIONTYPE,P10_LGR_WRITING_SAMPLE_IND:5491,24,Y
- [ ] https://jobs-airdc.icims.com/jobs/12974/research-summer-intern----youth%2c-family%2c-%26-community-development-%28masters-or-doctoral-students%29/job
```
