### ISSUE TITLE
0108

### ISSUE THREAD

**Issue by thin-lizard** [WeberLab-UW/LS-phd#96]
- [ ] [DRC new outline | LS-phd#19](https://github.com/PugetSoundClinic-PIT/LS-phd/issues/19)
    - [ ] abstract
    - [ ] 2x contributions - 
    - [ ] consistent terminology
    - [ ] focus group excerpts
    - [ ] discussion pgh
    - [ ] citations

- #101 

```[tasklist]
### Tasks
- [x] AWOLF
- [ ] BOOK REVIEW
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/65
- [ ] https://github.com/BITS-Research/DRC/issues/35
- [x] documentation ex.s
- [x] winter q milestones & plan
- [ ] 531 policy brief ex
- [x] 531 lessons // activities
- [ ] 531 writing clinic
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/72
- [x] 501 hw
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/43
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/55
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/54
- [ ] email meg young
- [ ] project imeline - workign w ols, farefair, ...
- [x] 531 grading
- [x] leo: pay scales; subsidized housing
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/73
- [x] 501
- [x] CDT INTERVIEW
- [ ] ABD paper...
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/74
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/75
- [ ] 571 assgt
- [ ] 501 assgt
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/102
- [ ] undergrad ra?
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/5
- [ ] https://github.com/PugetSoundClinic-PIT/LS-phd/issues/101
```
